// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMqYmvawYnGsDasWE_MhnY7acSQfG2_4U',
    appId: '1:506278642822:web:0242004434129f02543d07',
    messagingSenderId: '506278642822',
    projectId: 'flutterpinkuapp',
    authDomain: 'flutterpinkuapp.firebaseapp.com',
    storageBucket: 'flutterpinkuapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYU7mtYDVGOBsMwOMSUI5ygOkHywTyLg',
    appId: '1:506278642822:android:dc8f343733876874543d07',
    messagingSenderId: '506278642822',
    projectId: 'flutterpinkuapp',
    storageBucket: 'flutterpinkuapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbOO7ROxEbK4N_Nj3QB46LZih_2nNdW3M',
    appId: '1:506278642822:ios:c4629fb71acbbd28543d07',
    messagingSenderId: '506278642822',
    projectId: 'flutterpinkuapp',
    storageBucket: 'flutterpinkuapp.firebasestorage.app',
    iosBundleId: 'com.example.ytMusic',
  );
}
